#!/usr/bin/env bash

# This script displays a list of currently running processes.
# It shows all processes for all users, including those without a TTY.
# The output is displayed in a user-oriented format, including the process hierarchy.

ps axjf
