#!/usr/bin/env bash

pid_file="/var/run/myscript.pid"

# Function to handle SIGQUIT and SIGTERM signals
cleanup() {
    echo "Deleting $pid_file and terminating script."
    rm "$pid_file"
    exit 0
}

# Function to handle SIGINT signal
interrupt() {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
terminate() {
    echo "I hate the kill command"
}

# Trap signals
trap cleanup SIGQUIT SIGTERM
trap interrupt SIGINT
trap terminate SIGTERM

# Write PID to file
echo $$ > "$pid_file"

# Function to display "To infinity and beyond"
infinity() {
    echo "To infinity and beyond"
}

# Loop indefinitely
while true; do
    infinity
    sleep 1
done
